# Generated by Django 3.2.13 on 2022-07-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labdbAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meter_config',
        ),
    ]
