# Generated by Django 3.2.13 on 2022-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labdbAPI', '0002_delete_meter_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='meter_config',
            fields=[
                ('meterGUID', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('meterName', models.TextField(default='表')),
            ],
        ),
    ]
