# Generated by Django 3.2.13 on 2022-07-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdbAPI', '0003_meter_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='meter_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterGUID', models.CharField(max_length=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=-1.0)),
            ],
        ),
    ]
