# Generated by Django 3.2.13 on 2022-07-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdbAPI', '0004_meter_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.TextField(default='实验室')),
            ],
        ),
    ]
