# Generated by Django 3.2.13 on 2022-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdbAPI', '0005_lab_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_config',
            name='belongLab',
            field=models.TextField(default='测试实验室'),
            preserve_default=False,
        ),
    ]
