# Generated by Django 3.2.13 on 2022-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdbAPI', '0007_ai_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_process',
            name='previewImage',
            field=models.TextField(null=True),
        ),
    ]
